#=======================================================================================================================
server.port=8004
spring.application.name=transformation
#=======================================================================================================================
#引入公共的配置
spring.config.import[0]=optional:classpath:application-common.properties
#=======================================================================================================================
# sangsang
#自动从当前DataSource中获取表结构数据，某些语法下，必须知道哪些字段是表字段还是常量，所以必须读取整库的表结构信息
#默认就是开启的。使用此功能一定要确保开启此功能，不能关闭
sangsang.autoFill=true
#开启异构语法转换功能，选择oracle2mysql（自动将项目中oracle的语法转换为mysql的）
sangsang.transformation.patternType=oracle2mysql
#=======================================================================================================================