#=======================================================================================================================
server.port=8003
spring.application.name=sangsang-isolation
#=======================================================================================================================
#引入公共的配置
spring.config.import[0]=optional:classpath:application-common.properties
#=======================================================================================================================
# sangsang
#扫描@TableName的路径
sangsang.scanEntityPackage[0]=com.sangsang.demo.*.entity
#开启数据权限隔离功能
sangsang.isolation.enable=true
#=======================================================================================================================