#=======================================================================================================================
# mysql???????
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.url=jdbc:mysql://43.133.199.2:3307/sangsang?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
spring.datasource.username=sangsang
spring.datasource.password=sangsang
#=======================================================================================================================
#????sql????????????
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
#??xml???
mybatis.mapper-locations=classpath:mapper/*.xml
# ??????????
mybatis.configuration.map-underscore-to-camel-case=true
#=======================================================================================================================
# sangsang???
# ????????? ??????*??????* ? ???????????????@TableName?????????????????????
sangsang.scanEntityPackage[0]=com.sangsang.demo.*.entity
# ????????????????db??  ???????????????
sangsang.encryptor.patternType=db
# ?????????
sangsang.encryptor.secretKey=tired-of-the-water
#=======================================================================================================================
# Thymeleaf ??
# ????????????
spring.thymeleaf.check-template-location=true
# ????
spring.thymeleaf.encoding=UTF-8
# ????
spring.thymeleaf.servlet.content-type=text/html
# ??????????????? HTML ???????
spring.thymeleaf.cache=false
# ????????? (???????????)
spring.thymeleaf.prefix=classpath:/templates/
# ??????? (???????????)
spring.thymeleaf.suffix=.html
#=======================================================================================================================
server.port=8001