#=======================================================================================================================
server.port=8001
#=======================================================================================================================
#引入公共的配置
spring.config.import[0]=optional:classpath:application-common.properties
#=======================================================================================================================
# sangsang
#扫描@TableName的路径
sangsang.scanEntityPackage[0]=com.sangsang.demo.*.entity
#开启自动加解密功能，并设置模式是db
sangsang.encryptor.patternType=db
#自定义秘钥
sangsang.encryptor.secretKey=tired-of-the-water
#=======================================================================================================================